version: "3.9"

services:
  valkey:
    image: valkey/valkey:7-alpine
    container_name: valkey
    ports:
      - "6379:6379"        # expose to host for non-container clients
    volumes:
      - valkey_data:/data  # persist data locally
    command: ["valkey-server", "--appendonly", "yes"]

  touchpointmedical:
    container_name: touchpointmedical
    build:
      context: .
      dockerfile: TouchpointMedical.Site/Dockerfile
    depends_on:
      - valkey
    environment:
      # Inside the compose network, reach Valkey by its *service name* at port 6379
      - Cache__Endpoint=valkey:6379
      # any other app settings you need, e.g. ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      # keep your SQLite path the same as your current Dockerfile expects
      - ./TouchpointMedical.Site/App_Data:/app/App_Data
    # If you want the API to run with the Development environment:
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Development

volumes:
  valkey_data: